name: Build My Clock APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-24.04

    steps:

      # -----------------------------
      # دریافت پروژه
      # -----------------------------
      - name: Checkout
        uses: actions/checkout@v4


      # -----------------------------
      # Python مخصوص Buildozer
      # -----------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"


      # -----------------------------
      # Java 17
      # -----------------------------
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"


      # -----------------------------
      # نصب وابستگی‌های سیستم
      # -----------------------------
      - name: Install system dependencies
        run: |
          sudo apt-get update

          sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            autoconf \
            automake \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            cmake \
            libffi-dev \
            libssl-dev


      # -----------------------------
      # نصب Buildozer
      # -----------------------------
      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          python -m pip install buildozer
          python -m pip install "Cython==0.29.36"


      # -----------------------------
      # پاک کردن کش قبلی Buildozer
      # -----------------------------
      - name: Clean old Buildozer files
        run: |
          rm -rf .buildozer
          rm -rf bin


      # -----------------------------
      # ساخت APK
      # -----------------------------
      - name: Build APK
        run: |
          set -o pipefail
          buildozer -v android debug 2>&1 | tee build.log


      # -----------------------------
      # نمایش خطاهای واقعی
      # -----------------------------
      - name: Show important errors
        if: failure()
        run: |
          echo "=========================================="
          echo "IMPORTANT ERRORS"
          echo "=========================================="

          grep -nEi \
          "error:|error |failed|exception|traceback|fatal|not supported|command failed|buildozer failed" \
          build.log || true

          echo "=========================================="
          echo "LAST 150 LINES"
          echo "=========================================="

          tail -n 150 build.log


      # -----------------------------
      # آپلود APK
      # -----------------------------
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: My-Clock-APK
          path: bin/*.apk
